trigger: none

pool: powermanage-pool

steps:

- task: NodeAndNpmTool@1
  displayName: Install Nodejs version
  inputs:
    versionSpec: '16.x'

- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'

- task: Npm@1
  displayName: npm run build
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: PublishPipelineArtifact@1
  displayName: publish artifact
  inputs:
    targetPath: '$(Build.SourcesDirectory)/build'
    artifact: 'todoui'
    publishLocation: 'pipeline'

- task: ArchiveFiles@2
  displayName: Archive Artifact
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/todoui.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  displayName: publish artifact zip
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/todoui.zip'
    artifact: 'todoui.zip'
    publishLocation: 'pipeline'