trigger:
- none

pool: powermanage-pool


stages:
  - stage: Setup_nodejs
    displayName: Setup Nodejs
    jobs:
      - job: Install Nodejs
        steps:
        - checkout: self

        
          
            